const String showCourseById = r'''
query getRecordById($id: uuid!) {
  courses_by_pk(id: $id) {
    id
    created_at
    updated_at
    course_name
    course_category_id
    contact_name
    type
    startDate
    endDate
    startTime
    endTime
    presenters
    description
    address
    cpd_points
    number_of_seats
    early_bird_end_date
    early_bird_price
    afterwards_price
    topics_included
    learning_objectives
    event_type
    course_event_info
    sponsor_by_image
    course_banner_video
    course_banner_image
    course_gallery
    terms
    refund_policy
    company_name
    contact_email
    contact_phone
    contact_website
    status
    active_status
    register_link
    rsvp_date
    webinar_link
    youtube_link
    facebook_link
    instagram_link
    linkedin_link
    community_user_type
    module_section
    question_section
    pass_percentage
    is_lifetime
    course_access_duration
    module_details(order_by: {module_position: asc}) {
      id
      module_name
      expanded
      module_id
      course_id
      module_position
      section_details(order_by: {section_position: asc}) {
        id
        course_topic
        module_id
        description
        attachment
        expanded
        image
        status
        youtube_link
        section_position
        __typename
      }
      __typename
    }
    quiz_details(order_by: {quiz_position: asc}) {
      id
      question
      type
      course_id
      quiz_position
      quiz_id
      option_details(order_by: {option_position: asc}) {
        id
        isCorrect
        quiz_id
        text
        option_position
        __typename
      }
      __typename
    }
    __typename
  }
}
''';
