const String showCourseById = r'''
query getSelectedCourse($id: uuid!, $userId: uuid!) {
  courses_by_pk(id: $id) {
    id
    course_name
    is_featured
    number_of_seats
    address
    attachments
    course_event_info
    presenters
    seo_metadata
    sponsor_by_image
    afterwards_price
    cpd_points
    early_bird_price
    community_id
    community_user_type
    max_subscribers
    price_in_aud
    price_in_usd
    company_name
    complete_details
    contact_email
    contact_name
    contact_phone
    contact_website
    register_link
    description
    early_bird_end_date
    endDate
    event_type
    image
    learning_objectives
    module_section
    question_section
    pass_percentage
    refund_policy
    short_id
    short_info
    startDate
    status
    terms
    topics_included
    video
    webinar_link
    created_at
    scheduled_at
    updated_at
    course_category_id
    created_by_id
    course_banner_video
    course_gallery
    active_status
    startTime
    endTime
    type
    course_banner_image
    facebook_link
    instagram_link
    linkedin_link
    youtube_link
    course_registered_users(where: {from_id: {_eq: $userId}}) {
      id
      course_id
      from_id
      status
      quiz_status
      __typename
    }
    course_registered_users_aggregate(where: {status: {_neq: "CANCELLED"}}) {
      aggregate {
        count
        __typename
      }
      __typename
    }
    __typename
  }
}
''';
