final List<String> benifits = [
  "Performance bonus",
  "Commission",
  "Relocation fees",
  "Tips",
  "Overtime pay",
  "Signing Bonus",
  "Bonus",
  "Annual Bonus",
  "Quarterly bonus",
  "Employee Discount",
  "Visa sponsorship",
  "Employee Mentoring program",
  "Professional Development assistance",
  "Company car",
  "Travel reimbursement",
  "Housingallowance",
  "Other",
];
