const String getCourseDetailsQuery = r'''query getRecordById($id: uuid!) {
  courses_by_pk(id: $id) {
    id
    created_at
    updated_at
    course_name
    course_category_id
    contact_name
    type
    startDate
    endDate
    startTime
    endTime
    presenters
    description
    address
    cpd_points
    number_of_seats
    early_bird_end_date
    early_bird_price
    afterwards_price
    topics_included
    learning_objectives
    event_type
    course_event_info
    sponsor_by_image
    course_banner_video
    course_banner_image
    course_gallery
    terms
    refund_policy
    company_name
    contact_email
    contact_phone
    contact_website
    status
    active_status
    register_link
    rsvp_date
    webinar_link
    youtube_link
    facebook_link
    instagram_link
    linkedin_link
    community_user_type
    __typename
  }
}''';
