import 'package:flutter/material.dart';

class AppColors {
  AppColors._();
  static const Color primaryColor = Color(0xFFFF7000);
  static const Color whiteColor = Color(0xffFFFFFF);
  static const Color black = Color(0xff000000);
  static const Color hintColor = Color(0xffF9F9F9);
  static const Color bottomNavUnSelectedColor = Color(0xff748294);
  static const Color secondaryColor = Color(0xff021214);
  static const Color geryColor = Color(0xffCCCCCC);
  static const Color lightGeryColor = Color(0xff8A8A8F);
  static const HINT_COLOR = Color(0xffC2C2C2);
  static const Color PRIMARY_BLACK_COLOR = Color(0xFF202020);
  static const Color buttonColor = Color(0xFFFF7000);
  static const Color buttomBarColor = Color(0xFFEAEAEA);
  static const Color menuBGColor = Color.fromRGBO(204, 204, 204, 0.51);
  static const Color dividerColor = Color(0xFFC8C7CC99);
  static const Color bottomBarSelectIconColor = Color(0xFFBBBFD2);
  static const Color inputBorderColor = Color(0xFFDEDEDE);
  static const Color inputHintColor = Color(0xFF5B5772);
  static const Color backgroundColor = Color(0xFFEDEFF1);
  static const Color timeBgColor = Color(0xffFFF1E5);
  static const Color borderColor = Color(0xFFDCE0E4);
  static const Color clipBg = Color(0xff0471DE26);
  static const Color blueColor = Color(0xff0471DE);
  static const Color locationTextColor = Color(0xFF5F6B7A);
  static const Color secondaryBlueColor = Color.fromRGBO(4, 113, 222, 0.15);
  static const Color primaryBlueColor = Color(0xff0471de);
  static const Color dropDownHint = Color(0xffBAC1C8);
  static const Color greenColor = Color(0xff00934F);
  static const Color redColor = Color(0xffD71313);
  static const Color cardcolor = Color(0xffF6F7F9);
  static const Color greysecond = Color.fromRGBO(220, 224, 228, 1);
  static const Color pendingprimary = Color.fromRGBO(225, 146, 0, 0.1);
  static const Color pendingsendary = Color.fromRGBO(225, 146, 0, 1);
  static const Color activeprimary = Color.fromRGBO(0, 147, 79, 0.1);
  static const Color activesendary = Color.fromRGBO(0, 147, 79, 1);
  static const Color inactiveprimary = Color.fromRGBO(215, 19, 19, 0.1);
  static const Color inactivesendary = Color.fromRGBO(215, 19, 19, 1);
  static const Color timeblack = Color.fromRGBO(255, 241, 229, 0);
  static const Color timewhite = Color.fromRGBO(255, 241, 229, 1);
}
