const String getProfileByIdQuery = r'''query getJobProfilesById($id: uuid!) {
  job_profiles_by_pk(id: $id) {
    post_anonymously
    jobexperiences
    profile_image
    skills
    upload_resume
    admin_status
    current_company
    current_ctc
    email_address
    full_name
    home_address
    job_designation
    job_location
    mobile_number
    created_at
    updated_at
    location
    city
    country
    state
    profession_type
    work_type
    radius
    work_rights
    about_yourself
    location
    Year_of_experiance
    languages_spoken
    areas_expertise
    willing_to_travel
    travel_distance
    aphra_number
    availabilityOption
    availabilityDate
    fromDate
    abn_number
    id
    educations
    percentage
    certificate
    cover_letter
    availabilityDay
    salary_amount
    salary_type
    availabilityType
    unavailabilityDate
    __typename
  }
}''';