const String getTalentListByIdQuery =
    r'''query getTalentListMutationByid($id: uuid!) {
  job_profiles(where: {dental_professional_id: {_eq: $id}}) {
    id
    created_at
    updated_at
    dental_professional_id
    admin_status
    profile_image
    full_name
    mobile_number
    email_address
    skills
    jobexperiences
    educations
    upload_resume
    job_designation
    current_company
    current_ctc
    post_anonymously
    work_type
    professionType
    location
    country
    city
    state
    cover_letter
    certificate
    radius
    abn_number
    availabilityType
    availabilityOption
    availabilityDate
    availabilityDay
    work_rights
    Year_of_experiance
    languages_spoken
    areas_expertise
    percentage
    salary_amount
    salary_type
    aphra_number
    willing_to_travel
    travel_distance
    about_yourself
    fromDate
    dental_professional {
      id
      gender
      __typename
    }
    jobhirings {
      id
      dental_supplier_id
      dental_practice_id
      hiring_status
      __typename
    }
    __typename
  }
}''';
