const String practiceViewProfileQuery = r'''
query practiceDisplay($id: uuid!) {
  dental_practices_by_pk(id: $id) {
    id
    email
    name
    logo
    phone
    address
    city
    zipcode
    state
    country
    land_mark
    address_line_one
    address_line_two
    pro_details_aphra_registration_number
    bank_details
    business_name
    abn_number
    business_email
    business_phone
    mobile_number
    website_link
    fax_number
    alt_email
    alt_phone
    profession_type
    tga_number
    second_hand
    sell_products
    first_name
    middle_name
    last_name
    type
    secondary_contact
    __typename
  }
}
''';
