const String practiceViewProfileQuery = r'''
query practiceDisplay($id: uuid!) {
  dental_practices_by_pk(id: $id) {
    abn_number
    address
    alt_email
    alt_phone
    bank_details
    blocked_at
    blocked_reason
    business_email
    business_name
    business_phone
    contact_person_first_name
    contact_person_gender
    contact_person_last_name
    contact_person_middle_name
    contact_person_profile_image
    created_at
    credits
    defaultAddress
    directory_category_id
    directory_column_other_name
    driving_licence
    email
    email_verification_expiry_at
    email_verification_key
    email_verification_required
    email_verified
    fax_number
    first_name
    id
    last_name
    logo
    middle_name
    name
    passcode
    password
    password_reset_expiry_at
    password_reset_key
    password_reset_required
    payment_completed
    phone
    phone_verification_expiry_at
    phone_verification_key
    phone_verification_required
    phone_verified
    present_subscription_id
    pro_details_abn_acn_number
    pro_details_aphra_registration_number
    pro_details_driving_license_image
    pro_details_other_attachments
    pro_details_provider_number
    profession_type
    profile_completed
    profile_image
    second_hand
    secondary_contact
    sell_products
    status
    subsciption_plan_id
    tga_number
    timings
    type
    directories {
      id
      name
      email
      phone
      profile_image
      address
      profession_type
      __typename
    }
    __typename
  }
}
''';
